/* ============================================================================
 * MOCK DATA — DELETE FOR REAL DEPLOYMENT
 * ----------------------------------------------------------------------------
 * This file exists so the dashboard runs as a fully static site on GitHub Pages
 * with no backend. When you wire up the real Express API, delete this file and
 * flip the data source in `api.ts` (USE_MOCK). The shapes here match the real
 * NormalizedBet returned by GET /api/bets, so nothing else needs to change.
 * ==========================================================================*/

import type { Bet } from './types';

const RAW_MOCK: Omit<Bet, 'source'>[] = [
  {
    book: 'draftkings',
    betId: 'dk-1001',
    betType: 'single',
    status: 'settled',
    result: 'win',
    placedAt: '2026-06-28T23:10:00.000Z',
    settledAt: '2026-06-29T03:20:00.000Z',
    stake: 100,
    oddsAmerican: -110,
    potentialPayout: 190.91,
    payout: 190.91,
    currency: 'USD',
    legs: [
      {
        id: 'l1',
        selection: 'Boston Celtics -6.5',
        market: 'Point Spread',
        event: 'Celtics vs Knicks',
        oddsAmerican: -110,
        result: 'win',
      },
    ],
  },
  {
    book: 'draftkings',
    betId: 'dk-1002',
    betType: 'parlay',
    status: 'open',
    result: null,
    placedAt: '2026-07-03T18:45:00.000Z',
    settledAt: null,
    stake: 25,
    oddsAmerican: 465,
    potentialPayout: 141.25,
    payout: null,
    currency: 'USD',
    legs: [
      {
        id: 'l1',
        selection: 'Dodgers ML',
        market: 'Moneyline',
        event: 'Dodgers vs Padres',
        oddsAmerican: -140,
        result: null,
      },
      {
        id: 'l2',
        selection: 'Yankees ML',
        market: 'Moneyline',
        event: 'Yankees vs Red Sox',
        oddsAmerican: 120,
        result: null,
      },
      {
        id: 'l3',
        selection: 'Over 8.5 Runs',
        market: 'Total',
        event: 'Braves vs Mets',
        oddsAmerican: -105,
        result: null,
      },
    ],
  },
  {
    book: 'draftkings',
    betId: 'dk-1003',
    betType: 'single',
    status: 'settled',
    result: 'loss',
    placedAt: '2026-06-21T20:00:00.000Z',
    settledAt: '2026-06-21T23:30:00.000Z',
    stake: 75,
    oddsAmerican: 135,
    potentialPayout: 176.25,
    payout: 0,
    currency: 'USD',
    legs: [
      {
        id: 'l1',
        selection: 'Under 210.5 Points',
        market: 'Total Points',
        event: 'Warriors vs Suns',
        oddsAmerican: 135,
        result: 'loss',
      },
    ],
  },
  {
    book: 'draftkings',
    betId: 'dk-1004',
    betType: 'prop',
    status: 'settled',
    result: 'push',
    placedAt: '2026-06-18T19:00:00.000Z',
    settledAt: '2026-06-18T22:40:00.000Z',
    stake: 50,
    oddsAmerican: -115,
    potentialPayout: 93.48,
    payout: 50,
    currency: 'USD',
    legs: [
      {
        id: 'l1',
        selection: 'Aaron Judge Over 1.5 Total Bases',
        market: 'Player Total Bases',
        event: 'Yankees vs Orioles',
        oddsAmerican: -115,
        result: 'push',
      },
    ],
  },
  {
    book: 'fanduel',
    betId: 'fd-2001',
    betType: 'parlay',
    status: 'settled',
    result: 'win',
    placedAt: '2026-06-30T00:15:00.000Z',
    settledAt: '2026-06-30T04:00:00.000Z',
    stake: 40,
    oddsAmerican: 260,
    potentialPayout: 144,
    payout: 144,
    currency: 'USD',
    legs: [
      {
        id: 'l1',
        selection: 'Heat +3.5',
        market: 'Point Spread',
        event: 'Heat vs Bucks',
        oddsAmerican: -110,
        result: 'win',
      },
      {
        id: 'l2',
        selection: 'Jimmy Butler Over 22.5 PTS',
        market: 'Player Points',
        event: 'Heat vs Bucks',
        oddsAmerican: 105,
        result: 'win',
      },
    ],
  },
  {
    book: 'fanduel',
    betId: 'fd-2002',
    betType: 'single',
    status: 'open',
    result: null,
    placedAt: '2026-07-04T01:30:00.000Z',
    settledAt: null,
    stake: 60,
    oddsAmerican: -200,
    potentialPayout: 90,
    payout: null,
    currency: 'USD',
    legs: [
      {
        id: 'l1',
        selection: 'Chiefs -7.5',
        market: 'Point Spread',
        event: 'Chiefs vs Broncos',
        oddsAmerican: -200,
        result: null,
      },
    ],
  },
  {
    book: 'fanduel',
    betId: 'fd-2003',
    betType: 'single',
    status: 'settled',
    result: 'loss',
    placedAt: '2026-06-24T18:00:00.000Z',
    settledAt: '2026-06-24T21:15:00.000Z',
    stake: 120,
    oddsAmerican: -110,
    potentialPayout: 229.09,
    payout: 0,
    currency: 'USD',
    legs: [
      {
        id: 'l1',
        selection: 'Rangers ML',
        market: 'Moneyline',
        event: 'Rangers vs Astros',
        oddsAmerican: -110,
        result: 'loss',
      },
    ],
  },
  {
    book: 'prizepicks',
    betId: 'pp-3001',
    betType: 'dfs_entry',
    status: 'settled',
    result: 'win',
    placedAt: '2026-06-29T22:00:00.000Z',
    settledAt: '2026-06-30T02:30:00.000Z',
    stake: 20,
    oddsAmerican: null,
    potentialPayout: 100,
    payout: 100,
    currency: 'USD',
    legs: [
      {
        id: 'l1',
        selection: 'Shohei Ohtani',
        market: 'Total Bases • Over 1.5',
        event: 'Dodgers vs Giants',
        oddsAmerican: null,
        result: 'win',
      },
      {
        id: 'l2',
        selection: 'Mookie Betts',
        market: 'Hits+Runs+RBIs • Over 2.5',
        event: 'Dodgers vs Giants',
        oddsAmerican: null,
        result: 'win',
      },
      {
        id: 'l3',
        selection: 'Freddie Freeman',
        market: 'Total Bases • Over 1.5',
        event: 'Dodgers vs Giants',
        oddsAmerican: null,
        result: 'win',
      },
    ],
  },
  {
    book: 'prizepicks',
    betId: 'pp-3002',
    betType: 'dfs_entry',
    status: 'settled',
    result: 'loss',
    placedAt: '2026-06-26T23:30:00.000Z',
    settledAt: '2026-06-27T03:00:00.000Z',
    stake: 25,
    oddsAmerican: null,
    potentialPayout: 250,
    payout: 0,
    currency: 'USD',
    legs: [
      {
        id: 'l1',
        selection: 'Luka Doncic',
        market: 'Points • Over 29.5',
        event: 'Mavericks vs Nuggets',
        oddsAmerican: null,
        result: 'win',
      },
      {
        id: 'l2',
        selection: 'Nikola Jokic',
        market: 'Rebounds • Over 12.5',
        event: 'Mavericks vs Nuggets',
        oddsAmerican: null,
        result: 'loss',
      },
    ],
  },
  {
    book: 'prizepicks',
    betId: 'pp-3003',
    betType: 'dfs_entry',
    status: 'open',
    result: null,
    placedAt: '2026-07-03T21:00:00.000Z',
    settledAt: null,
    stake: 10,
    oddsAmerican: null,
    potentialPayout: 30,
    payout: null,
    currency: 'USD',
    legs: [
      {
        id: 'l1',
        selection: 'Aaron Judge',
        market: 'Home Runs • Over 0.5',
        event: 'Yankees vs Rays',
        oddsAmerican: null,
        result: null,
      },
      {
        id: 'l2',
        selection: 'Juan Soto',
        market: 'Total Bases • Over 1.5',
        event: 'Yankees vs Rays',
        oddsAmerican: null,
        result: null,
      },
    ],
  },
];

// League tags let the ESPN layer match each demo bet to a real game.
const LEAGUE_BY_ID: Record<string, string> = {
  'dk-1001': 'nba',
  'dk-1002': 'mlb',
  'dk-1003': 'nba',
  'dk-1004': 'mlb',
  'fd-2001': 'nba',
  'fd-2002': 'nfl',
  'fd-2003': 'mlb',
  'pp-3001': 'mlb',
  'pp-3002': 'nba',
  'pp-3003': 'mlb',
};

export const MOCK_BETS: Bet[] = RAW_MOCK.map((b) => ({
  ...b,
  source: 'manual',
  league: LEAGUE_BY_ID[b.betId] ?? null,
}));
/* ======================= END MOCK DATA ==================================== */
